version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:alpine
    labels:
      - "name=redis"
      - "mode=standalone"
    platform: linux/amd64
    ports:
      - "6379:6379"
  db:
    container_name: database
    image: mariadb:10
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=pickgether
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
  pick-app:
    container_name: pick-app
    build: .
    depends_on:
      - db
      - redis
    image: moonsungkim/pick-app
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always